version: 43.0.9
pageUuid: c94b6684-1e5e-11eb-96a6-4f7f29ee9fc6
appTemplate:
  urlFragmentDefinitions: []
  pageLoadValueOverrides: []
  customDocumentTitle: ''
  isGlobalWidget: false
  isFetching: false
  instrumentationEnabled: false
  customDocumentTitleEnabled: false
  version: 2.64.32
  responsiveLayoutDisabled: false
  createdAt: null
